# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('abstract', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('a', 'Approved'), ('s', 'Submitted'), ('r', 'Rejected')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=20)),
                ('twitter', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('descriptions', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.AddField(
            model_name='session',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Speaker'),
        ),
        migrations.AddField(
            model_name='session',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Track'),
        ),
    ]
