# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20170604_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('subdomain', models.CharField(max_length=63, unique=True, verbose_name='Organization Subdomain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_owner', to=settings.AUTH_USER_MODEL, verbose_name='Organization Owner')),
            ],
        ),
    ]
