# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170607_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('a', 'Approved'), ('s', 'Submitted'), ('r', 'Rejected'), ('p', 'pending')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userstripe',
            name='stripe_id',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
