# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170608_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='session',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='session',
            name='track',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstripe',
            name='user',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.DeleteModel(
            name='userStripe',
        ),
    ]
